spring:
  application:
    name: Contactability Test
  main:
    headless: true

contactability:
  service:
    host: contactability.appslatam.com
    port: 443
    audience: 32555940559.apps.googleusercontent.com
  test:
    max-api-calls: ${CONTACTABILITY_TEST_MAX_API_CALLS:100}

logging:
  level:
    root: WARN
    cl:
      latam:
        contactabilitytest: INFO
